/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Categories: typeof import('./../src/layouts/categories.vue')['default']
    CommonBlock: typeof import('./../src/components/common/block.vue')['default']
    CommonButton: typeof import('./../src/components/common/button.vue')['default']
    CommonCard: typeof import('./../src/components/common/card.vue')['default']
    CommonLink: typeof import('./../src/components/common/link.vue')['default']
    CommonProgressbar: typeof import('./../src/components/common/progressbar.vue')['default']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    Home: typeof import('./../src/layouts/home.vue')['default']
    IndexContent: typeof import('./../src/components/index/content.vue')['default']
    IndexLeftMenu: typeof import('./../src/layouts/indexLeftMenu.vue')['default']
    IndexTopMenu: typeof import('./../src/layouts/indexTopMenu.vue')['default']
    LinkGroup: typeof import('./../src/components/link/group.vue')['default']
    MenuBubble: typeof import('./../src/components/menu/bubble.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestPage: typeof import('./../src/layouts/testPage.vue')['default']
    TransitionScaleOpacity: typeof import('./../src/components/transition/scaleOpacity.vue')['default']
  }
}
