/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommonBlock: typeof import('./../src/components/common/block.vue')['default']
    CommonButton: typeof import('./../src/components/common/button.vue')['default']
    CommonLink: typeof import('./../src/components/common/link.vue')['default']
    Home: typeof import('./../src/layouts/home.vue')['default']
    IndexTopMenu: typeof import('./../src/layouts/indexTopMenu.vue')['default']
    MenuBubble: typeof import('./../src/components/menu/bubble.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
